FROM microsoft/dotnet:2.0.0-runtime

COPY ./publish/HtmlRefresh /app
WORKDIR /app

EXPOSE 5000/tcp

ARG ARG_HTML_REFRESH_BGCOLOUR
ARG ARG_HTML_REFRESH_FGCOLOUR

ENV HTML_REFRESH_BGCOLOUR $ARG_HTML_REFRESH_BGCOLOUR
ENV HTML_REFRESH_FGCOLOUR $ARG_HTML_REFRESH_FGCOLOUR
ENV HTML_REFRESH_MESSAGE "%HOSTNAME%"
ENV ASPNETCORE_URLS=http://*:5000

ENTRYPOINT ["dotnet", "HtmlRefresh.dll"]

