FROM golang:alpine as build
ADD ./src /src
RUN cd /src/HtmlRefresh && go build

FROM alpine
WORKDIR /app
COPY --from=build /src/HtmlRefresh /app
EXPOSE 8080

ARG ARG_HTML_REFRESH_BGCOLOUR
ARG ARG_HTML_REFRESH_FGCOLOUR

ENV HTML_REFRESH_BGCOLOUR $ARG_HTML_REFRESH_BGCOLOUR
ENV HTML_REFRESH_FGCOLOUR $ARG_HTML_REFRESH_FGCOLOUR

ENTRYPOINT [ "./HtmlRefresh" ]